---
version: '3'

tasks:
  apply:
    desc: Apply
    cmds:
      - terraform apply -var-file=env_vars/pve04.tfvars
  init:
    desc: Init
    cmds:
      - terraform init
  plan:
    desc: Plan
    cmde:
      - terraform plan -var-file=env_vars/pve04.tfvars
  decrypt:
    desc: Decrypt vars using SOPS
    cmds:
      - sops -d --input-type dotenv --output-type dotenv env_vars/pve04.tfvars.enc > env_vars/pve04.tfvars
  encrypt:
    desc: Encrypt vars using SOPS
    cmds:
      - sops -e --input-type dotenv --output-type dotenv env_vars/pve04.tfvars > env_vars/pve04.tfvars.enc
  default:
    cmds:
      - task -l
    silent: true
