---
version: '3'

tasks:
  apply:
    desc: Apply
    cmds:
      - terraform apply -var-file=secrets.tfvars
  init:
    desc: Init
    cmds:
      - terraform init
  plan:
    desc: Plan
    cmde:
      - terraform plan -var-file=secrets.tfvars
  decrypt:
    desc: Decrypt vars using SOPS
    cmds:
      - sops -d --input-type dotenv --output-type dotenv secrets.tfvars.enc > secrets.tfvars
  encrypt:
    desc: Encrypt vars using SOPS
    cmds:
      - sops -e --input-type dotenv --output-type dotenv secrets.tfvars > secrets.tfvars.enc
  default:
    cmds:
      - task -l
    silent: true
